name: Cypress Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cypress run
        uses: ./
        with:
          working-directory: examples/component-tests
          component: true
